Repository kubeshop/kusk, pull requests merged in 2021-08, with the labels that each got.

#103 docs: add ArgoCD guide
  docs/argocd.md
Labels: area/documentation, kind/feature

#112 Add support for generating nginx ingress resources to kusk wizard
  cluster/cluster.go
  wizard/wizard.go
Labels: area/generators, kind/feature

#114 Update docs with brew command
  README.md
  docs/getting-started.md
Labels: area/documentation, kind/enhancement

#120 Update issue templates with kind labels
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: kind/cleanup, area/org

#137 nginx-ingress: add rate limit options
  docs/nginx-ingress.md
  generators/nginx_ingress/annotations.go
  generators/nginx_ingress/nginx_ingress.go
  generators/nginx_ingress/nginx_ingress_test.go
  options/options.go
  options/ratelimit.go
  options/service.go
  options/timeout.go
Labels: area/generators, area/documentation, kind/feature

#140 nginx-ingress: fix incorrect host command line option
  generators/nginx_ingress/nginx_ingress.go
Labels: area/cli, area/generators, kind/bug

#141 CORS options support in Wizard
  wizard/flow/ambassador.go
  wizard/flow/nginx_ingress.go
  wizard/prompt/prompt.go
Labels: area/cli, kind/enhancement
